from .extractive_question_answering import ExtractiveQuestionAnsweringTaskModule
from .re_text_classification_with_indices import (
    RETextClassificationWithIndicesTaskModule,
)
from .token_classification import TokenClassificationTaskModule
